### ISSUE TITLE
"About" is too wide on mobile

### ISSUE THREAD

**Issue by cariad** [cariad/rust.coffee#8]
It's those darned non-breaking spaces in the title.

**Comment by abitsalihu** [comment]
Hey @cariad, I would like to help on this issue. :)

**Comment by cariad** [comment]
@abitsalihu Awesome! Submit a pull request and I'll review it today!

It's just a one-line change. I put some non-breaking spaces in the title of the "about" page because I didn't want the site title to break between lines, but that makes the title too long on mobile. All we need to do is replace the non-breaking spaces with regular spaces. 

Let me know if you need a hand finding the line, otherwise I'll look out for your PR!

**Comment by abitsalihu** [comment]
Hey @cariad, this is the first time trying to manipulate files made with rust witch css, I saw the problem but the only way I could fix it is by doing `overflow-wrap: break-word;` on he `h1`, but even that does not fix it completely for a bizarre reason it won't make the word break but the letters.

Below is a picture of the problem with borders to see what is happening, and a video of the fix I did `(don't mind the borders I added for visualization)` :

The problem `(the h1 overflows and doesn't break when the screen is small) :

<img width="339" alt="Screen Shot 2022-09-25 at 12 01 25" src="https://user-images.githubusercontent.com/94648837/192139104-5c521dd0-7c44-4143-abab-bea029810a44.png">

The fix I managed to do using `overflow-wrap: break-word ;` :  


https://user-images.githubusercontent.com/94648837/192139181-84383f12-0c4d-4b01-9be0-2f6f6aec7cf2.mov


Please tell me if I should proceed with a PR with the fix I made, or you wish to find a different method to fix it. :)

**Comment by cariad** [comment]
Hey @abitsalihu! I appreciate all that effort!

To clarify, when I said "All we need to do is replace the non-breaking spaces with regular spaces." I literally meant we only need to replace the `&nbsp;` characters in [content/about.md](https://github.com/cariad/rust.coffee/blob/b0ad73775e1dacd1288b8582578437869fab52f2/content/about.md?plain=1#L3). We don't need any CSS changes -- just something like this:

```diff
date: 2022-09-23
- title: About ✨rust&nbsp;&&&nbsp;coffee✨
+ title: About ✨rust && coffee✨
type: page
```

This probably isn't as exciting a PR as you were hoping for! 😅

**Comment by abitsalihu** [comment]
@cariad lol, I got it now, sorry this is the first time I'm seeing rust code 😅, but I'll make the changes you requested and make the PR. This was exciting enough to learn something new! 😁

**Comment by cariad** [comment]
@abitsalihu Absolutely no problem, I promise! No rush, no sweat. 😁

**Comment by cariad** [comment]
Fixed in https://github.com/cariad/rust.coffee/pull/11 - thank you!
